spring:
  dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jsonToken?createDatabaseIfNotExist=true
    user: jwt
    password: test

  jpa:
    hibernate:
      ddlAuto: create
#      ddlAuto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.springframework.web: info
    org.springframework.security: trace