
spring:
  profiles:
    include: oauth
---

spring:
  dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guestbookdb?createDatabaseIfNotExist=true
    user: bookuser
    password: test


  jpa:
    hibernate:
#      ddlAuto: create
      ddlAuto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      location: /Volumes/Public/Project/Millie/guestbook/img
      maxRequestSize: 30MB
      maxFileSize: 10MB

# 파일 저장 위치
com:
  example:
    guestbook:
      path: /Volumes/Public/Project/Millie/guestbook/img

# 로그 레벨 조정
logging:
  level:
    org.springframework.web: info
    org.springframework.security: trace

#    com:
#      example:
#        guestbook: debug
    "org.springframework: security" : trace
#    org.springframework: info
#    com.example.guestbook: debug
#    "[org.springframework.security]": trace


#level:
#  logging:
#    org:
#      springframework:
#        security:
#          debug: trace

#  docker exec -it mysql-container mysql -u root -p


#  docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root --name mysql-container mysql:latest
#  docker run -d -p 3306:3306 mysql_root_password=root --name mysql-container mysql:latest