spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 7b79be59c74b48c06de7e2edca45885d
            redirect_uri: "http://localhost:8080/login/oauth2/code/kakao"
#            client-authentication-method: POST
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-secret: h3iyaPxOIlJLKwkTTdwv4Ij1SayqixV5
            scope:
              - profile_nickname
              - profile_image

        provider:
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth2/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-name-attribute: