<<<<<<< HEAD
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jsonToken?createDatabaseIfNotExist=true
    user: jwt
    password: test

=======
Spring:
  dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guestbookdb?createDatabaseIfNotExist=true
    user: bookuser
    password: test


>>>>>>> f7fe66ec2943220f6e9af5cb9c30275f9e291f79
  jpa:
    hibernate:
#      ddlAuto: create
      ddlAuto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

<<<<<<< HEAD
logging:
  level:
    org.springframework:web: info
    org.springframework:security: trace


com:
  example:
    jwt:
      secret: hi1234567
=======
level:
  logging:
    org:
      springframework:
        security:
          debug: trace

#  docker exec -it mysql-container mysql -u root -p


#  docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root --name mysql-container mysql:latest
#  docker run -d -p 3306:3306 mysql_root_password=root --name mysql-container mysql:latest
>>>>>>> f7fe66ec2943220f6e9af5cb9c30275f9e291f79
